### ISSUE TITLE
关于Edgeless的实现思路与WTG融合的展望——ENW：Edgeless's Not Wimboot（稍长）

### ISSUE THREAD

**Issue by WeiguangTWK** [Cnotech/Edgeless-Project#58]
现阶段的Edgeless已经相当完美，这些只是个人的一点思考和实践，仅作意见

我尝试使用Edgeless整合一个可移动生产环境遭遇了不少阻碍，最终采用了一个相对妥协的方案——开启了UWF的VHD化Windows To Go与Edgeless PE共存同一U盘

- 我希望达成的效果：
1.整合所有需要的工具
2.拥有非常可观的兼容性（因为用于启动的PC配置是不断不断变动的，搞不好还会遇上跑Win7的老爷机）
3.灵活性和较低的修改成本（因为生产环境会经常变动）
4.软件难以损坏（因为操作者小白居多）
5.尽量快速

目前Edgeless面对这些需求唯一不满足的地方——配置兼容性，也就是第二点

因为在乡镇机关这种电脑配置普遍落后的地方，4GB RAM的电脑占比其实非常高
而要满足 Edgeless本体 + 生产环境插件 + 给软件正常运行腾出来的RAM——需要的内存已经远高于4GB

于是在探索理想效果的过程中诞生了以下想法，经实践确认其可行性

完全固化不可修改的WTG + Edgeless模式的插件加载

完全固化不可修改通过统一写入筛选器实现

> 统一写入筛选器 (UWF) 是一个可选的 Windows 10 功能，它通过拦截驱动器的所有写入（应用安装、设置更改、保存的数据）并将其重定向到虚拟覆盖层来帮助保护驱动器。 虚拟覆盖是一个临时位置，通常在重新启动期间或来宾用户注销时清除

- 实现关键——“统一写入筛选器” （UWF）【Windows 企业版/教育版】
这里简述WTG开启UWF的特点：重启还原，提升速度，兼容提升

重启还原、兼容提升：
同样是重启还原，相比WinPE的将整个系统放至RAM运行，UWF只将“临时修改”存放在RAM，而系统本体仍然是通过直接读取U盘的VHD使用，这将大大降低对于电脑RAM的硬性需求

提升速度：
UWF开启后Windows会自动将分页文件，SuperFetch等服务关闭，并且对于系统盘的操作将仅限于读取（在此情景下即对于U盘VHD文件的读取），而写入会被重定向至RAM的“覆盖层”，不仅降低U盘的压力而且提升WTG运行速度

那么面对固化的系统需要灵活进行模块化修改，Edgeless的思路在此仍然可行

最终效果：

- 与Edgeless软件包加载器一同通过UWF固化的WTG的VHD文件 + Edgeless外部软件包(7z) + Ventoy + Ventoy_VHDBoot

同样软件包加载器沿袭Edgeless的“寄生”概念，故取名为

Edgeless's
Not
Wimboot
——ENW

**Comment by Cnotech** [comment]
所以你是自己做了一个只读的WTG+Edgeless包管理？

**Comment by Cnotech** [comment]
嗯...我觉得Edgeless PE的产品定位还是非常清晰的，我们不考虑兼容性，因此你的这个需求确实和我们的预设场景存在偏差，需要自己做一些解决方案出来。
之后Edgeless会专注于Windows下的包管理解决方案，希望能为你的WTG提供一些支持。

**Comment by WeiguangTWK** [comment]
> 所以你是自己做了一个只读的WTG+Edgeless包管理？

我确实做了一个只读的WTG，但是Edgeless包管理我没有搞明白，因此只是个设想
