### ISSUE TITLE
[hub]: 大佬，win端制作优盘的软件，连接不上服务器了，下载不了必须配件

### ISSUE THREAD

**Issue by e7naq3y** [Cnotech/Edgeless-Project#61]
### Official Wiki

- [X] I've checked the official Wiki throughout.

### Ventoy Wiki

- [X] This is not a Ventoy self issue or a hardware incompatible problem.

### Edgeless Hub Version

2.27

### What about the latest release?

- [X] Yes. That still happens.

### Which version of Windows are you using?

Windows 11

### What happened?

大佬，win端制作优盘的软件，连接不上服务器了，下载不了必须配件

**Comment by Cnotech** [comment]
目前菠萝云的服务器确实出现了断线问题，可以先使用下载站下载
