### ISSUE TITLE
[hub]: 

### ISSUE THREAD

**Issue by GitHubUserC** [Cnotech/Edgeless-Project#63]
### Official Wiki

- [X] I've checked the official Wiki throughout.

### Ventoy Wiki

- [X] This is not a Ventoy self issue or a hardware incompatible problem.

### Edgeless Hub Version

2.27

### What about the latest release?

- [X] Yes. That still happens.

### Which version of Windows are you using?

Windows 11

### What happened?

![image](https://github.com/EdgelessPE/Edgeless/assets/25133322/dd77ff75-18b2-4cd9-8565-8201d80d4149)
电信宽带、联通手机开热点、移动手机开热点，均无法正常访问pineapple.edgeless.top域名，挂代理后翻出去以后反而能访问，感觉这个域名被墙了？是否考虑支持国内镜像？

**Comment by Cnotech** [comment]
为避免重复issue，统一在此处跟踪此缺陷哈：https://github.com/EdgelessPE/Edgeless/issues/64
