### ISSUE TITLE
[website]: 菠萝云好像崩了?

### ISSUE THREAD

**Issue by Jimme** [Cnotech/Edgeless-Project#64]
### What happened?

从Hub到网站都无法下载

**Comment by Cnotech** [comment]
菠萝云增加了waf策略，暂时不可用；最近hub打赢复活赛了，之后看看能不能支持改源

**Comment by LLL151** [comment]
> 菠萝云增加了waf策略，暂时不可用；最近hub打赢复活赛了，之后看看能不能支持改源

什么时候能够恢复使用呢

**Comment by KJZH001** [comment]
请问有无手动部署的说明？我之前本地已经下好了edgelesshub需要的文件，但也还是由于无法连接服务器导致卡住无法自动部署

目前在尝试手动执行ventoy的安装步骤，然后看看能否正常引导运行

**Comment by Cnotech** [comment]
手动部署的文档：https://wiki.edgeless.top/v2/guide/burn_manual.html
最近工作比较忙，我尽可能在这周末完成hub的更新工作

**Comment by KJZH001** [comment]
> 手动部署的文档：https://wiki.edgeless.top/v2/guide/burn_manual.html 最近工作比较忙，我尽可能在这周末完成hub的更新工作

好的，感谢回复

**Comment by Cnotech** [comment]
已更新下载站，下载2.28版本hub即可
