### ISSUE TITLE
[kernel]: 能否使 Ventoy 分区可隐藏

### ISSUE THREAD

**Issue by Ikaleio** [Cnotech/Edgeless-Project#65]
### Official Wiki

- [X] I've checked the official Wiki throughout.

### Maybe it's a hardware incompatible problem?

Yes. I use Edgeless with modern hardware.

### Edgeless Version

3.2.0

### What about alpha release?

Yes. I have tried the latest alpha release.

### What happened?

Ventoy 制作完成后，Ventoy 分区可设为隐藏，以防止正常使用 U 盘时陌生电脑安全软件误杀，~~同时也更好看~~。

但 Ventoy 分区隐藏后 Edgeless 无法加载插件，是否可以在 Edgeless 启动时强制将 Ventoy 分区挂载而忽略隐藏标志？

**Comment by Cnotech** [comment]
没太理解，是指名称为Ventoy的分区吗？这个分区还可以用来存文件的为啥要隐藏呢

**Comment by Ikaleio** [comment]
那个分区用于存 ventoy 启动的各种镜像和 edgeless 数据，根目录有一堆wim和iso 很丑

如果隐藏文件会被杀毒软件报毒

**Comment by Ikaleio** [comment]
ventoy 本身就有提供“在硬盘后保留空间”的功能，且在分区表中隐藏ventoy分区不影响使用

**Comment by Cnotech** [comment]
pe本体最近不太会有更新了，用hub制作启动盘之后可以把wim文件移动到自定义的子目录里面去，只要Edgeless文件夹不动就能继续被hub识别下载插件包。

当然如果你觉得这些东西都应该放到后面的分区里面藏起来，那很抱歉我无能为力，请自行修改开源代码实现你想要的功能

**Comment by Ikaleio** [comment]
那请问开机时挂在分区是哪一部分的代码？对PE开发没什么经验

**Comment by mcl44** [comment]
> 那个分区用于存 ventoy 启动的各种镜像和 edgeless 数据，根目录有一堆wim和iso 很丑
> 
> 如果隐藏文件会被杀毒软件报毒

第一，ventoy没有规定镜像一定要放在根目录下，详情参见ventoy官方文档。
第二，所谓“在硬盘后保留空间”，只是单纯不把那一部分硬盘空间格式化而已。
第三，你所谓的隐藏文件很模糊，是把文件隐藏，还是把可见文件放在隐藏分区。
第四，ventoy官方文档解释过隐藏分区的问题。win10（具体版本我记不清，参考ventoy官方文档）之后，MBR格式的分区无法默认隐藏，即便本机隐藏换到另外一台主机上还是会显示（dg行不行我也没试过），GPT格式分区默认隐藏ventoy启动分区

**Comment by mcl44** [comment]
> ### Official Wiki
> * [x]  I've checked the official Wiki throughout.
> 
> ### Maybe it's a hardware incompatible problem?
> Yes. I use Edgeless with modern hardware.
> 
> ### Edgeless Version
> 3.2.0
> 
> ### What about alpha release?
> Yes. I have tried the latest alpha release.
> 
> ### What happened?
> Ventoy 制作完成后，Ventoy 分区可设为隐藏，以防止正常使用 U 盘时陌生电脑安全软件误杀，~同时也更好看~。
> 
> 但 Ventoy 分区隐藏后 Edgeless 无法加载插件，是否可以在 Edgeless 启动时强制将 Ventoy 分区挂载而忽略隐藏标志？

“ventoy分区隐藏后edgeless无法加载插件”，第一，edgeless插件加载是读取普通分区根目录下的edgeless文件夹下的resources文件夹，和ventoy启动分区没关系；第二，你所谓的ventoy分区是指什么，按你的描述我实在无法理解

**Comment by mcl44** [comment]
> 那请问开机时挂在分区是哪一部分的代码？对PE开发没什么经验

解决方案逻辑上没问题，但是pe开机后是加载到内存的，也就是X盘，所以在edgeless启动时强制挂载ventoy存储分区已经没有任何作用。如果你觉得根目录放一堆文件不好看，可以自行组织目录，ventoy默认是遍历所有目录
