### ISSUE TITLE
[kernel]: 在安装了扩展驱动插件和主系统导出的驱动后依然无法正常驱动硬盘工作

### ISSUE THREAD

**Issue by KJZH001** [Cnotech/Edgeless-Project#66]
### Official Wiki

- [X] I've checked the official Wiki throughout.

### Maybe it's a hardware incompatible problem?

Yes. I use Edgeless with modern hardware.

### Edgeless Version

4.1.0

### What about alpha release?

No. I don't know where to get alpha release.

### What happened?

首先，这是我目前的插件包

```
D:\Edgeless\Resource 的目录

2019/01/26  15:15    <DIR>          .
2019/01/26  15:15    <DIR>          ..
2019/02/16  21:00                14 一键启用所有插件.cmd
2019/02/16  21:00                14 一键禁用所有插件.cmd
2019/07/25  10:30         8,777,654 搜狗拼音_8.4.0.1039_Cno.7z
2024/05/27  13:33       133,256,012 Firefox_125.0.3.0_Cno（bot）.7z
2024/05/27  13:32         1,408,096 Intel+VMD驱动_20.0.0.1037_HHJLKK.7z
2024/05/27  13:32         8,391,245 Xshell_7.0.0008.0_Cno.7z
2024/05/27  13:31        15,495,076 微软mstsc远程桌面_10.0.18362.0_Oxygen.7z
2024/05/31  15:53        88,057,991 网卡增强驱动_1.1.0_Fir.7z
2024/05/31  15:53        21,836,394 基本无线网卡驱动_1.0.0.0_光卡.7z
2024/05/31  15:53         2,866,333 IRST_18.0.4.1146_Oxygen.7z
2024/05/31  15:52         2,894,576 AdbUSBDriver_11.1_Ran.7z
2024/05/31  15:52        10,368,866 硬盘增强驱动_1.0.0_Fir.7z
2024/05/31  16:02         5,030,491 晓空_驱动插件包_1.0.0.0.7z
              13 个文件    298,382,762 字节
               2 个目录 119,781,195,776 可用字节
```
另外，我按照**[为Edgeless添加自定义驱动（插件包法） | Edgeless Wiki](https://wiki.edgeless.top/v2/playground/driver.html)
wiki.edgeless.top**的说明，将主系统的存储控制器驱动全部导出

![image](https://github.com/EdgelessPE/Edgeless/assets/29683578/a1a366a5-b752-404d-9b28-eeda676b4800)

然后打包为了一个插件（即上文的晓空_驱动插件包_1.0.0.0.7z）

最后得到的结果是，系统识别到了硬盘驱动器，但是无法工作

![](https://img.cdn.18g.me/2024/06/665d1da54f714.jpg)

该设备无法启动（代码10）

**Comment by KJZH001** [comment]
另外我注意到目前访问wiki.edgeless.top会被强制无限重定向到wiki.edgeless.top/v2

这可能是配置故障，且在无痕模式下能稳定复现

**Comment by Cnotech** [comment]
<img width="465" alt="image" src="https://github.com/EdgelessPE/Edgeless/assets/53827731/81724dce-1332-4f0b-a06f-a699ab786f83">
PE的环境是精简版本的Windows，所以这种方法确实无法保证能完美驱动所有硬件，可以尝试使用些驱动安装软件

**Comment by KJZH001** [comment]
> <img alt="image" width="465" src="https://private-user-images.githubusercontent.com/53827731/335924417-81724dce-1332-4f0b-a06f-a699ab786f83.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTczODQxMjcsIm5iZiI6MTcxNzM4MzgyNywicGF0aCI6Ii81MzgyNzczMS8zMzU5MjQ0MTctODE3MjRkY2UtMTMzMi00ZjBiLWEwNmYtYTY5OWFiNzg2ZjgzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAzVDAzMDM0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4MTQxZmUzMWJlZjE2ZTg3NWNmMGExZTgwMTUyZGM5MmVhNDkwMzYyN2E2YmY4YWI2MDNiZmJiMTlkNjUwNjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IE6wt-IHW1rkM4Kl5_SFdJPZqFzs_FGdyu_mu0V3vEg"> PE的环境是精简版本的Windows，所以这种方法确实无法保证能完美驱动所有硬件，可以尝试使用些驱动安装软件

抱歉，是我没有表达清楚我的意思，我明白这并不能驱动所有硬件，所有我想知道的是，接下来有哪些可以建议我尝试的步骤呢？

作为维护主操作系统的PE，如果读取不到硬盘，那么也就失去了绝大多数的功能，这也是我在尝试寻找一个兼容性更好的pe的原因，奇怪的是，在此前基本上没有碰到的硬盘驱动的问题在近些年似乎尤其突出

我注意你说了驱动安装软件，您是指这些用于完整系统的驱动工具（例如驱动精灵的离线版）可以在edgeless上运行吗？我曾经在某些比edgeless更为精简的pe上尝试过他们，并不能正常工作

**Comment by KJZH001** [comment]
经过测试，驱动总裁网卡版内置的网卡驱动打上后，从服务器安装硬盘驱动可以正常看到硬盘，问题解决

**Comment by mcl44** [comment]
> 经过测试，驱动总裁网卡版内置的网卡驱动打上后，从服务器安装硬盘驱动可以正常看到硬盘，问题解决

只要解决了网络问题，其他的都可以自行尝试啊，没网那是绝对困难（如wepe），其他的都是相对的。
