### ISSUE TITLE
[kernel]: 无法更改分辨率，只能显示800X600的分辨率

### ISSUE THREAD

**Issue by herolulu** [Cnotech/Edgeless-Project#67]
### Official Wiki

- [X] I've checked the official Wiki throughout.

### Maybe it's a hardware incompatible problem?

Yes. I use Edgeless with modern hardware.

### Edgeless Version

4.1.0

### What about alpha release?

No. I don't know where to get alpha release.

### What happened?

我的电脑分辨率支持1920X1080. 虽然右下角修改分辨率的软件有对应的分辨率，但是点击修改无效。只能显示800X600的分辨率。用微PE的时候是可以显示1920X1080的。

**Comment by herolulu** [comment]
我是用ventoy 导入ISO启动的。

**Comment by herolulu** [comment]
家里的电脑是去年买的组装机主板微星Z790，公司是19年的联想品牌机，目前都有这个问题。然后又试了firepe可以显示大分辨率。 XD

**Comment by Cnotech** [comment]
ventoy导入iso启动会有这个问题，建议通过hub制作或参考手动制作wiki，这样制作的启动盘支持在启动引导时更改分辨率

**Comment by Cnotech** [comment]
相关wiki：https://wiki.edgeless.top/v2/faq/resolution.html https://wiki.edgeless.top/v2/guide/burn_manual.html

**Comment by herolulu** [comment]
非常感谢

**Comment by herolulu** [comment]
搞定了，多谢大佬
