### ISSUE TITLE
[kernel]: iso文件VMware workstation pro 17.5.2启动长时间黑屏

### ISSUE THREAD

**Issue by mcl44** [Cnotech/Edgeless-Project#68]
### Official Wiki

- [X] I've checked the official Wiki throughout.

### Maybe it's a hardware incompatible problem?

Yes. I use Edgeless with modern hardware.

### Edgeless Version

beta 4.1.0

### What about alpha release?

No. I don't know where to get alpha release.

### What happened?

环境：
- VMware workstation pro 17.5.2
- 内存RAM 4.8G
- 光驱 CD/DVD(SATA)
- iso版本 Edgeless_beta_4.1.0.iso

启动引导正常，win10logo加载完成后可以看到一闪而过的cmd窗口，然后持续黑屏。iso文件是hub自动生成，实体机测过ventoy方式可以启动，iso实体机没测过

**Comment by Cnotech** [comment]
我自己测试是用的vmware16没问题，我有空试下17

**Comment by Cnotech** [comment]
![image](https://github.com/user-attachments/assets/aafb2677-35eb-4582-8f29-5d40f9342de0)
我用的17.5.1是可以正常启动的，建议检查下iso文件的MD5：35887B073DE3FD07FA23A3602BE811EC

**Comment by mcl44** [comment]
> ![image](https://private-user-images.githubusercontent.com/53827731/356586546-aafb2677-35eb-4582-8f29-5d40f9342de0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyNzMwMzIsIm5iZiI6MTcyMzI3MjczMiwicGF0aCI6Ii81MzgyNzczMS8zNTY1ODY1NDYtYWFmYjI2NzctMzVlYi00NTgyLThmMjktNWQ0MGY5MzQyZGUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEwVDA2NTIxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExMzIzM2Q2ZjRhZTg1M2NjZGIzYWY0YTRmMGNmNTZhNWM1YmFkNzBjOWVkNDg2MTI5M2JiNmRmOTJlMGFlNTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5Xl0sho-WVVihlnMXAqbTZOsC12qvFQlza5NJ8wHNaQ) 我用的17.5.1是可以正常启动的，建议检查下iso文件的MD5：35887B073DE3FD07FA23A3602BE811EC

iso的md5经校验没有问题，可能17.5.2有什么隐藏bug。感谢🙇

**Comment by mcl44** [comment]
> ![image](https://private-user-images.githubusercontent.com/53827731/356586546-aafb2677-35eb-4582-8f29-5d40f9342de0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyNzMwMzIsIm5iZiI6MTcyMzI3MjczMiwicGF0aCI6Ii81MzgyNzczMS8zNTY1ODY1NDYtYWFmYjI2NzctMzVlYi00NTgyLThmMjktNWQ0MGY5MzQyZGUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEwVDA2NTIxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExMzIzM2Q2ZjRhZTg1M2NjZGIzYWY0YTRmMGNmNTZhNWM1YmFkNzBjOWVkNDg2MTI5M2JiNmRmOTJlMGFlNTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5Xl0sho-WVVihlnMXAqbTZOsC12qvFQlza5NJ8wHNaQ) 我用的17.5.1是可以正常启动的，建议检查下iso文件的MD5：35887B073DE3FD07FA23A3602BE811EC

这个虚拟机的配置可以发一下吗，我想看一下有没有什么遗漏的地方

**Comment by Cnotech** [comment]
![image](https://github.com/user-attachments/assets/44780a15-ec3a-448e-ab27-ccaebc6126ea)
![image](https://github.com/user-attachments/assets/6175306e-6a5b-4fd0-8562-8da4a4eee4c1)

**Comment by mcl44** [comment]
😂问题排查完毕，黑屏原因在于：虚拟机设置 > 选项 > 常规 > 客户机操作系统，操作系统及版本选择了“其他 64位”。修改为microsoft windows的Windows 10 x64/WindowsNT后成功进入桌面。原理尚不清楚，不过Wepe_V2.3.iso经试验不受客户机操作系统版本影响（实际上只试了“其他 64位”）
