### ISSUE TITLE
[website]: 内测群已满员

### ISSUE THREAD

**Issue by xrgzs** [Cnotech/Edgeless-Project#69]
### What happened?

想要反馈一些问题，还有联系获取授权，发现内测群已满员无法加入😥

https://home.edgeless.top/jump/qqg.html

内测交流2群 1146253726

![](https://github.com/user-attachments/assets/7836305b-9263-42a1-a502-085473a3beb5)

**Comment by Cnotech** [comment]
get，预期在本周完成清理工作

**Comment by Cnotech** [comment]
目前群的活跃人数仍然超过了群人数上限，可以先在这里询问问题或申请授权

**Comment by xrgzs** [comment]
我在项目（潇然PE启动，https://pe.xrgzs.top/ ）中模块化地使用了Edgeless作为网络插件包加载来源，并且制作了Edgeless插件包下载器GUI，希望能够获取授权，避免侵权盗用。我可以协助Edgeless团队维护插件包更新。

申请授权内容：

- 使用“Edgeless”文本字样进行非商业非盈利性宣传
- 将Edgeless提供的遵循MPL-2.0协议的开源代码包含在项目内以实现非商业用途
- 使用Edgeless官方渠道为项目提供插件包
- 以包括侧载（sideloading）、模块化等方式使项目具有支持 Edgeless 相关功能的能力

**Comment by Cnotech** [comment]
授权信息已添加到： https://wiki.edgeless.top/v2/cooperation/%E6%BD%87%E7%84%B6PE.html

第四点（侧载支持）是第三点的子集，因此只要有三项即可
