### ISSUE TITLE
[kernel]: wim无法启动

### ISSUE THREAD

**Issue by llwijvbw123** [Cnotech/Edgeless-Project#70]
### Official Wiki

- [X] I've checked the official Wiki throughout.

### Maybe it's a hardware incompatible problem?

Yes. I use Edgeless with modern hardware.

### Edgeless Version

4.1.0

### What about alpha release?

Yes. I have tried the latest alpha release.

### What happened?

![1725781706688](https://github.com/user-attachments/assets/4a6bafce-d8af-4e99-b75e-55a07b453010)
安装完成后，U盘(128G 海视威康)启动，选择Edgeless_Beta_4.1.0.wim 就会报如图的错，但手上的别一个U盘（4G），也是一样的版本，就正常。

**Comment by Cnotech** [comment]
尝试使用Rufus：https://wiki.edgeless.top/v2/playground/no-ventoy.html
另外海康等固态u盘确实存在驱动问题，建议使用非固态u盘
