### ISSUE TITLE
咨询一个比较低级的问题，我是个小白

### ISSUE THREAD

**Issue by bingbaicai** [Cnotech/Edgeless-Project#71]
我也是第一次接触这个edgeless
我用这个制作了1个U盘，我U盘里面放了win10的纯净版，也下载了一些安装后常用的办公聊天软件之类。
但是我进edgeless里面用里面的工具安装这个系统后他并没有自动安装我下载的那些软件
请问这个问题我该如何解决呢
我如果直接进edgelessPE 里面他那些软件会自动安装
我想达到的效果是我安装完纯净版的win10后他能自动把我下载到U盘里面的那些在制作U盘时候下载的软件自动安装完成。
请这里的大佬们在百忙之中给我解答一下

**Comment by Cnotech** [comment]
PE里面的插件包只能在PE环境里面用，不是给安装好的系统使用的。你的这个需求可以去看看[Windsys](https://windsys.win/)推出的 [WTDR.PACK](https://wtdr.whatk.me/WP_Docs/#wtdr-pack-%E6%98%AF%E4%BB%80%E4%B9%88)

比较进阶的玩法是可以写个脚本修改部署后系统的启动项，然后调用 winget 或者 scoop 之类的包管理工具安装你需要的软件，这个点等新版 ept 开发完成后可能会出配套的工具包自动做这件事
