### ISSUE TITLE
内测群已满

### ISSUE THREAD

**Issue by HAIN-ITDev** [Cnotech/Edgeless-Project#72]
如题，内侧2群已满，拿到了问题答案仍然进不去
![image](https://github.com/user-attachments/assets/2045fa96-07f0-4d56-b52d-e1a6b8b9406b)

**Comment by HAIN-ITDev** [comment]
Github不常看 可能要等等......

**Comment by Cnotech** [comment]
关联： https://github.com/EdgelessPE/Edgeless/issues/69 ；由于目前无法联系上群主，并且活跃用户已经大于群上限，暂时无法升级成员上限，有问题可以先在 issue 提问
