### ISSUE TITLE
qq群已满人，没有找到提交插件方法

### ISSUE THREAD

**Issue by Genshinzmnl** [Cnotech/Edgeless-Project#73]
你好，我遇到的问题如标题所示，我不能获取到关于比Edgeless高级会员制2群更新的群的添加方式，这似乎是唯一的提交插件包的方式

**Comment by Cnotech** [comment]
关联：#72 #69 

我先去找下腾讯客服吧，看看能不能帮忙扩到500人

**Comment by Cnotech** [comment]
腾讯这客服和没有没区别...服了

如果需要提交插件请尽量使用Edgeless Bot，可以通过pr将任务提交到next分支，由于历史原因手动封装的插件包之后会逐渐废弃

**Comment by Genshinzmnl** [comment]
好的，谢谢
