### ISSUE TITLE
[hub]:新版hub创建&识别USB有误（含临时问题解决方式）

### ISSUE THREAD

**Issue by Thomas20090425** [Cnotech/Edgeless-Project#74]
### Official Wiki

- [X] I've checked the official Wiki throughout.

### Ventoy Wiki

- [X] This is not a Ventoy self issue or a hardware incompatible problem.

### Edgeless Hub Version

2.28

### What about the latest release?

- [X] Yes. That still happens.

### Which version of Windows are you using?

Windows 10

### What happened?

您好开发者，如题,

我是一名初中留学生，很小的时候就来了所以中文不是很好麻烦谅解。

**_大概遭遇：_**
Edgeless Hub现在似乎在创建USB有问题，我不是很确定为何以前没有这个issue，或许我是第一个遇到这个问题的。我尝试了3台电脑（2台win11，1台win10）2个不同的USB创建之后分别没有被Edgeless Hub检测到，Edgeless Hub会提示成功，但是软件会提示 “无法进行配置，未检测到Edgeless启动盘，请先执行写入步骤”，然而在explorer里可以确定Edgeless的文件的确存在。文档里的更改ventoy写入的方式并不奏效，再次根据稳定排错，在console里显示”无法访问 A:\“所以我用diskgen把usb改成了盘符”A:\“然而这个时候console里彻底没东西了。
大概第二天的时候（也就是今天）我懵打蒙撞导致软件给了一个错误，有点类似于访问不了Edgeless某一个路径的错误"\Edgeless\Resource"然后我就发现了Edgeless似乎在我20多次的重新制作里没有一次的成功的创建了Resource这个文件夹。

_**解决方式：**_
 手动创建Resource这个文件夹解决了这个问题。

_**我这边可能存在的问题：**_
您有提到英语版本的windows11系统可能有其他问题，这边我的两台windows 11电脑分别都是英语的系统，windows10的电脑是从法语改成英语再改成中文的系统，3台电脑系统并非都是原装中文的系统，这有可能是“不清楚bug"里的其中一个。

_**文档修改建议/我的猜测**_
我有手动更改hub的config文件
_原：_
`{"stationIndex":0,"theme":"light","downloadDir":"C:\\Users\\Thomas\\Downloads\\HubCache","userName":"Thomas","alphaCode":"","showConfirmDialog":false,"ignore_notice_id":"0"}`
_修改后_
`{"stationIndex":0,"theme":"light","downloadDir":"C:\\Users\\Thomas\\Downloads\\HubCache","userName":"Thomas","alphaCode":"","showConfirmDialog":false,"ignore_notice_id":"1"}`
如果`ignore_notice_id`是和报错有关的话，为了排错的简单性建议把0改为1

_**总结**_
_问题_：Edgeless Hub不主动创建Resouce文件导致软件不识别
_解决方式_：手动在 `VentoyUSB:\Edgeless`里面创建`Resource`文件。路径应该类似于`D:\Edgeless\Resource`

感谢作者/开发者阅读，和您所有投入到这个project的精力！
- Thomas

**Comment by Cnotech** [comment]
感谢你的反馈😘

制作启动盘时会对是否缺少 \Edgeless\version.txt 进行检查，如果检查未通过会弹出错误提示，但是你遇到的问题是因为 Resource 目录没有被创建导致的，这个确实没有被报告过，有可能是因为系统语言不为简体中文或者被某些杀毒软件拦截导致的，我稍后会尝试用虚拟机安装一个英文版的 Windows 10 复现一下你的问题。

`ignore_notice_id` 是用来忽略从服务器接收的公共通知的，和制作过程没有关系。

请问在你手动创建 Recource 目录后 Hub 是否能正常工作了呢？是否还会出现尝试读取 A:\ 然后报错的情况？

**Comment by Cnotech** [comment]
已在英文版 Windows 11 上确认 Resource 目录无法被创建的问题，但是中文版上确实是没有这个问题的，稍后会抽空进行修复

**Comment by Thomas20090425** [comment]
没错，手动创建`Resource`文件夹可以临时解决问题。感谢您的回复！如果您希望的话，可以暂时在Document里添加这个解决方式。

- Thomas

**Comment by Cnotech** [comment]
已在 2.29 版本中修复此问题，麻烦验证一下，感谢~

**Comment by Thomas20090425** [comment]
新版2.9，问题已解决！感谢您！

- Thomas
