### ISSUE TITLE
[kernel]: 进系统后黑屏

### ISSUE THREAD

**Issue by Thomas20090425** [Cnotech/Edgeless-Project#75]
### Official Wiki

- [X] I've checked the official Wiki throughout.

### Maybe it's a hardware incompatible problem?

Yes. I use Edgeless with modern hardware.

### Edgeless Version

3.2.0

### What about alpha release?

Yes. I have tried the latest alpha release.

### What happened?

具体情况：
[https://github.com/Thomas20090425/Thomas20090425/releases/download/hi/WIN_20241111_21_04_43_Pro.mp4](url)
有了解文档，不过确实没有解释这种进系统完全没反应的情况，Ventoy有更改为GPT格式而且SecureBoot也关闭了，我再试试在我的BIOS和GPU上下手吧。

设备型号：Lenovo Workstation S30

**Comment by Cnotech** [comment]
<img width="1009" alt="image" src="https://github.com/user-attachments/assets/012d6a19-a66a-407c-a701-7a2ac7adf281">

这里启动的是 Edgeless 的 wim 文件嘛？是因为被重命名了？

因为你的机型比较老，兼容性方面确实会存在问题，可以尝试下用 Edgeless(1024x768) 的启动项试一下；或者参考 https://wiki.edgeless.top/v2/playground/no-ventoy.html 使用 Rufus 制作启动盘

**Comment by Thomas20090425** [comment]
是Edgeless，是被重命名了，我给我的一个项目整合的恢复包。这里有可能是兼容性问题，1024x768也是不可以的，您给的这个方法我一会试试，谢谢您！

- Thomas

**Comment by Thomas20090425** [comment]
本机问题，原来的bios似乎对win10不是很好，从而导致黑屏，更新bios解决问题！

- Thomas
