### ISSUE TITLE
[kernel]: 在PE中登录Samba时出现“指定的登录会话不存在，可能已被终止。”

### ISSUE THREAD

**Issue by a492219408** [Cnotech/Edgeless-Project#76]
### Official Wiki

- [X] I've checked the official Wiki throughout.

### Maybe it's a hardware incompatible problem?

Yes. I use Edgeless with modern hardware.

### Edgeless Version

4.1.0

### What about alpha release?

No. I don't know where to get alpha release.

### What happened?

<img width="512" alt="Snipaste_2024-11-16_02-06-59" src="https://github.com/user-attachments/assets/aec6ec4c-5f66-406d-bdf2-65a93a4893c7">
在PE中登录Samba时出现“指定的登录会话不存在，可能已被终止。”

**Comment by a492219408** [comment]
已解决，参考[此文档](https://kb.synology.com/en-global/DSM/tutorial/specified_logon_session_does_not_exist_error_message_SMB)

**Comment by Cnotech** [comment]
是因为要填写`Server name of your NAS\Your user name`吗
